version: '3'
services:
  server:
    container_name: go-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - server:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - go-react

  client:
    image: node:alpine
    container_name: webpack
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - webpack:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - go-react

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - go-react

volumes:
  webpack:
  server:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  go-react:
    driver: bridge
